### PR TITLE
Merge upstream into PR for resolution of issue #337 in CanCanCan

### PR DESCRIPTION
**Pull request by zachweed**
This should resolve the merge conflicts associated with upstream changes after creation of PR [#363](https://github.com/CanCanCommunity/cancancan/pull/363)

Everything looks good on my end. If I missed anything, just let me know and I'll make the appropriate changes :)

### CODE REVIEW

**Comment by zachweed** [comment]
@mtrudel no rush on this, but I wanted to check if you had a chance to take a look at this. I'd prefer to not have to deal with another avalanche of upstream changes haha :)

**Comment by mtrudel** [comment]
Oh jeez - I never got a notification for this. Looking right now.

**Comment by mtrudel** [comment]
LGTM (also, WOW are things changing fast and furious on cancancan - great to see!)

**Comment by mtrudel** [comment]
@zachweed merged

**Pull request merged**
